general.live_config_reload = true

# Font
[font]
size = 15.0

# alacritty.toml

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1
# decorations = "full"
padding = { x = 10, y = 10 }

# Kanagawa Wave Alacritty Colors

[colors.primary]
background = '#111111'
foreground = '#dddddd'

# [colors.normal]
# black = '#090618'
# red = '#c34043'
# green = '#76946a'
# yellow = '#c0a36e'
# blue = '#7e9cd8'
# magenta = '#957fb8'
# cyan = '#6a9589'
# white = '#c8c093'
#
# [colors.bright]
# black = '#727169'
# red = '#e82424'
# green = '#98bb6c'
# yellow = '#e6c384'
# blue = '#7fb4ca'
# magenta = '#938aa9'
# cyan = '#7aa89f'
# white = '#dcd7ba'
#
# [colors.selection]
# background = '#2d4f67'
# foreground = '#c8c093'
#
# [[colors.indexed_colors]]
# index = 16
# color = '#ffa066'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#ff5d62'
